// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeNav
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeNavToolWindowPackageString = "5c1c8131-1371-4401-8a3e-70e47c8ac0ec";
        public static Guid guidCodeNavToolWindowPackage = new Guid(guidCodeNavToolWindowPackageString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeNavToolWindowCommandId = 0x0100;
    }
}