namespace CodeNav.Models
{
    public enum CodeItemKindEnum
    {
        Unknown,
        All,
        Class,
        Constant,
        Constructor,
        Delegate,
        Enum,
        EnumMember,
        Event,
        ImplementedInterface,
        Indexer,
        Interface,
        Method,
        Namespace,
        Property,
        Region,
        Struct,
        Switch,
        SwitchSection,
        Variable,
        LocalFunction,
        BaseClass,
        StyleRule,
        PageRule,
        NamespaceRule,
        MediaRule,
        FontFaceRule,
        Record
    }
}
