name: CodeNav

on:
  push:
    branches:
      - main
      - 'feature/**'

env:
  version: '10.1.${{ github.run_number }}'
  dotnetVersion: '8'
  repoUrl: ${{ github.server_url }}/${{ github.repository }}
  vsixPath: ${{ github.workspace }}/src/CodeNav/bin/Release/net472/CodeNav.vsix

jobs:
  build:
    name: 🛠️ Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.dotnetVersion }}.x

      - name: Restore/Build/Test
        run: dotnet test

      - name: Update Vsix Manifest Version
        id: vsix_version
        uses: timheuer/vsix-version-stamp@v2
        with:
          version-number: ${{ env.version }}
          manifest-file: src/CodeNav/source.extension.vsixmanifest

      - name: Build VSIX
        run: dotnet publish src/CodeNav -p:Version=${{ env.version }} -c Release

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: CodeNav
          path: |
            ${{ env.vsixPath }}
            publish-manifest.json
            README.md

  release:
    if: github.ref_name == 'main'
    name: 🚀 Release
    needs: build
    runs-on: windows-latest
    environment: Release
    permissions:
        contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8

      - name: Create and Tag release
        uses: ncipollo/release-action@v1.20.0
        with:
          commit: ${{ github.sha }}
          tag: 'v${{ env.version }}'
          artifacts: ${{ env.vsixPath }}
          generateReleaseNotes: true
          skipIfReleaseExists: true

      - name: Publish to Marketplace
        uses: cezarypiatek/VsixPublisherAction@1.1
        with:
          extension-file: ${{ env.vsixPath }}
          publish-manifest-file: publish-manifest.json
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}

      - name: Publish to Open VSIX Gallery
        uses: timheuer/openvsixpublish@v1
        with:
          vsix-file: ${{ env.vsixPath }}